import Link from 'next/link';

export const metadata = { title: 'Terms of Use' };

export default function TermsPage() {
  return (
    <article className="reader mx-auto max-w-2xl">
      <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Terms of Use</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: 15 June 2026</p>

      <div className="prose-note mt-6">
        <p>
          By using CruxAI you agree to these terms. CruxAI is a free, open-source
          service provided as-is.
        </p>

        <h2>Your content</h2>
        <p>
          You are responsible for the files and links you submit, and you confirm you
          have the right to use them. Do not upload content you are not allowed to
          process. You keep all rights to your own content.
        </p>

        <h2>Acceptable use</h2>
        <p>
          Don&apos;t use CruxAI for anything illegal, abusive, or that infringes others&apos;
          rights, and don&apos;t attempt to disrupt or overload the service.
        </p>

        <h2>AI output</h2>
        <p>
          Summaries, quizzes and answers are generated by AI and may contain mistakes.
          They are a study aid, not professional, legal, medical or academic advice.
          Always verify important facts against the source.
        </p>

        <h2>Availability</h2>
        <p>
          The service may change or be unavailable at times. As a free project, we
          provide no uptime guarantee and no warranty of any kind.
        </p>

        <h2>Open source</h2>
        <p>
          CruxAI&apos;s source code is open under the MIT license. You can review or
          self-host it from the{' '}
          <a href="https://github.com/tamerlanmusayev" target="_blank" rel="noreferrer">
            GitHub repositories
          </a>
          .
        </p>

        <h2>Liability</h2>
        <p>
          To the extent permitted by law, CruxAI and its author are not liable for any
          damages arising from use of the service.
        </p>

        <h2>Contact</h2>
        <p>Questions about these terms? Reach us through GitHub.</p>
      </div>

      <Link href="/" className="mt-8 inline-block text-sm text-brand hover:underline">
        ← Back to CruxAI
      </Link>
    </article>
  );
}
